import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api/api.service';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-short-url',
  templateUrl: './short-url.component.html',
  styleUrls: ['./short-url.component.scss']
})
export class ShortUrlComponent implements OnInit {

url; // short url generated by the server API
url_original; // Original url entered by user
url_vanity; // Custom url name entered by user
status; // Status returned by the server API
result; // Result returned by the server API
url_short: Subscription; 

constructor(
  private router: Router,
  private ApiService: ApiService
) { }

/**
 * Calls the UrlShort function
 */
ngOnInit(): void {
  // Angular Lifecycle Stages Hooks
  // OnInit, OnChanges ( Input Changes ), OnDestoy
 // this.url_original = this.ApiService.url_original;
 // this.url_vanity = this.ApiService.url_vanity;
  this.UrlShort()
}

/**
 * Description: Unsubscribe to the server API
 */
ngOnDestroy() {
  this.url_short.unsubscribe();
}

/**
 * Description: Calls the Success function if no error occur else calls the Error function if error is present
 */
UrlShort() {
  this.url_short = this.ApiService.UrlShort().subscribe(
    res => this.Success(res),
    err => this.Error(err)
  )
}

/**
 * Description: On success, assigns the short url obtained from server, result and status appropriately
 * @param res : response
 */
Success(res) {
  console.log("res = ",res);
  this.url = res.url;
  if(res.statusCode =='100')
    this.status = 'Url add successfully';
  else if(res.statusCode =='400')
    this.status = 'Failed';
  else if(res.statusCode =='401')
    this.status = 'Entered url not reacheble';
  else if(res.statusCode =='402')
    this.status = 'Url not entered';
  else if(res.statusCode =='403')
    this.status = 'Custom url contains invalid characters(0-9,a-z,A-Z are only accepted)';
  else if(res.statusCode =='404')
    this.status = 'Url not found';
  else if(res.statusCode =='405')
    this.status = 'Custom url too long';
  else if(res.statusCode =='406')
    this.status = 'Url entered too long';
  else if(res.statusCode =='407')
    this.status = 'Custom url too short, enter min 5 characters';    
  else if(res.statusCode =='408')
    this.status = 'Limit reached by user per hour';
  this.result = res.result;
  console.log("url=",this.url, this.result, this.status);
}

/**
 * Description: Displays the error occured
 * @param err : error
 */
Error(err) {
  console.log(err)
}

/**
 * Description: Connects with the API service to generate the short URL for the original URL and custom name(optional) entered by user 
 */
onUrlShort() {
  this.ApiService.url_original = this.url_original;
  this.ApiService.url_vanity = this.url_vanity;
  this.UrlShort()
}


}

